channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - ipdb=0.12
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - isort=4.3.20
  - mccabe=0.6.1
  - mypy=0.701
  - mypy_extensions=0.4.1
  - pycodestyle=2.5.0
  - pydocstyle=3.0.0
  - pylint=2.3.1
  - python=3.7.3
  - vulture=1.0

